server:
  port: 9001
  servlet:
    context-path: /api
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${mongodb+srv://serverconnection:XeLNDTdl8tFmC2xa@mflix-jho7e.mongodb.net/test?retryWrites=true&w=majority}
      database: ${database:dev}
